#!/bash

# Any failure causes exit
set -e

echo Setting RAILS_ENV=test RACK_ENV=test
export RAILS_ENV=test RACK_ENV=test

base_dir=$PWD
tmp_dir=$base_dir/tmp
railsapp=$tmp_dir/railsapp
custom_file="$railsapp/tmp/custom_check.ok"
catchall_file="$railsapp/tmp/catchall_route.enabled"
success=successful

rails="rails"
rake="rake"

# if [ -x $base_dir/test/bin/rails ]
# then
#     rails="$base_dir/test/bin/rails"
#     rake="$base_dir/test/bin/rake"
#     export PATH="$base_dir/test/bin:$PATH"
# fi

# if [ -x $railsapp/bin/rails ]
# then
#     rails="$railsapp/bin/rails"
#     rake="$railsapp/bin/rake"
#     export PATH="$railsapp/bin:$PATH"
# fi

echo "Using rails=$rails, rake=$rake"